import type { DocumentModel, Point } from '../app/types';
import { polygonBounds } from '../geometry/polygon';

function pointList(points: Point[]) {
  return points.map((point) => `[${point.x.toFixed(3)}, ${point.y.toFixed(3)}]`).join(', ');
}

export function exportScad(document: DocumentModel) {
  const { molleParams } = document;
  const bounds = polygonBounds(document.outline);
  const enabledSlots = document.slots.filter((slot) => slot.enabled);

  return `// Generated by AMC - Advanced Molle Creator
$fn=100;

plateThickness = ${molleParams.plateThickness};
boltDiameter = ${molleParams.boltDiameter};
nutDiameter = ${molleParams.nutDiameter};
nutHeight = ${molleParams.nutHeight};

module panel_shape(){
  translate([${-bounds.minX.toFixed(3)}, ${-bounds.minY.toFixed(3)}, 0])
    polygon(points=[${pointList(document.outline)}]);
}

module slot(x, y, w, h){
  translate([x, y, -1]) cube([w, h, plateThickness + 2]);
}

module bolt(x, y){
  translate([x, y, -1]) cylinder(plateThickness + 2, boltDiameter / 2, boltDiameter / 2);
  translate([x, y, plateThickness - nutHeight]) cylinder(nutHeight + .1, nutDiameter / 2, nutDiameter / 2, $fn=6);
}

difference(){
  linear_extrude(height=plateThickness) panel_shape();

${enabledSlots
  .map((slot) => {
    const x = slot.x - bounds.minX;
    const y = slot.y - bounds.minY;
    const cx = x + slot.width / 2;
    return `  slot(${x.toFixed(3)}, ${y.toFixed(3)}, ${slot.width.toFixed(3)}, ${slot.height.toFixed(3)});\n  bolt(${cx.toFixed(3)}, ${(y - molleParams.slotGapY / 2).toFixed(3)});\n  bolt(${cx.toFixed(3)}, ${(y + slot.height + molleParams.slotGapY / 2).toFixed(3)});`;
  })
  .join('\n')}
}
`;
}
